### ISSUE TITLE
otlp-proto-grpc default exporter appears to break auto-instrumentation

### ISSUE THREAD

**Issue by jeremydvoss** [open-telemetry/opentelemetry-python-contrib#1189]
**Describe your environment**
Windows 11 - Python 3.10.4 - Local OT 1.12.0rc1-0.31b0
Ubuntu 20/04 - Python 3.8.10 - Local OT 1.12.0rc1-0.31b0

**Steps to reproduce**
Checkout e27f2b866bd840623bb128a1c04296c52b35b919 in core repo. This is the final rc1 commit.
Checkout 51ba801bfda31c3d57902d9f9df938cee1236eb8 in contrib repo. This is the commit that added grpc for auto-instrumentation.
Follow [these instructions](https://opentelemetry.io/docs/instrumentation/python/automatic/) to trigger auto-instrumentation.
This should produce multiple errors on Linux and Windows saying:
`RuntimeError: Requested component 'otlp_proto_grpc' not found in entry points for 'opentelemetry_metrics_exporter'`

**What is the expected behavior?**
The above case should produce no errors. To see what that should look like, here is a control case.
Remain at e27f2b866bd840623bb128a1c04296c52b35b919 in core repo. This is the final rc1 commit.
Rewind one commit to ad15f7bc8271dad44774cfb6e510c49d34c4100c in contrib repo. This is the commit before adding grpc for auto-instrumentation.
Follow [these instructions](https://opentelemetry.io/docs/instrumentation/python/automatic/) to trigger auto-instrumentation.
This should produce no errors. Instead, you should only see output along the lines of:
``` * Serving Flask app 'server_uninstrumented' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8082 (Press CTRL+C to quit)
```

**What is the actual behavior?**
`RuntimeError: Requested component 'otlp_proto_grpc' not found in entry points for 'opentelemetry_metrics_exporter'`

**Additional context**

**Comment by jeremydvoss** [comment]
The PR in question is [this](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1127)

**Comment by srikanthccv** [comment]
Fixed https://github.com/open-telemetry/opentelemetry-python/pull/2748. Please use rc2 version.

**Comment by jeremydvoss** [comment]
This problem still exists in rc2. I'm using contrib commit 127518bb55a9a81d39d56a964040e829bab0c1b9 and core commit fe26adaa07f88324c933a75f1a4dd199c9c8b2d7. The problem exists for me for every commit since those I identified in the description.

**Comment by srikanthccv** [comment]
Can you share your pip freeze output?

**Comment by Yamakaky** [comment]
I have the same issue. I tried to set `OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf` but this env var doesn't seem to be used in the sdk?

**Comment by lzchen** [comment]
@Yamakaky 
Is this issue even related? Are you having the same problem as https://github.com/open-telemetry/opentelemetry-python/issues/2586

**Comment by Yamakaky** [comment]
I have the same initial problem, and additionally the env variable doesn't work.

**Comment by lzchen** [comment]
@jeremydvoss 
What was the resolution of the above issue? Could you provide some guidance?
